In [1]:
import cPickle as cp
import numpy as np
import matplotlib.pyplot as plt
from __future__ import division

X, y = cp.load(open('data/voting.cPickle', 'rb'))

N, D = X.shape
N_train = int(0.8 * N)
N_test = N - N_train
X_train = X[:N_train]
y_train = y[:N_train]
X_test = X[N_train:]
y_test = y[N_train:]

report_string = "{}\nTrain: {:.5f}\nTest:  {:.5f}"

/Users/rb/anaconda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')


In [6]:
from scipy.stats import norm
from math import log

class NBC:
    def __init__(self, feature_types, num_classes):
        self.feature_types = feature_types
        self.num_features = len(feature_types)
        self.num_classes = int(num_classes)
        self.classes = None
        self.class_map = None
        self.logpi = None
        self.logprob = None
        
    
    def fit(self, X, y):
        if self.logpi != None:
            raise Exception("Already fitted")
        if X.shape[1] != self.num_features:
            raise Exception("Wrong number of features")
            
        self.classes = np.unique(y)
        if len(self.classes) != self.num_classes:
            raise Execption("Wrong number of classes")
        self.class_map = {v: k for k, v in np.ndenumerate(self.classes)}
            
        self.logpi = np.log([np.count_nonzero(y == c) for c in self.classes]) - log(y.shape[0])
        
        def theta(class_, features):
            data = [X[i] for i in range(0,X.shape[0]) if y[i] == self.class_map[class_]
            return [np.mean(data),np.std(data)];
        thetas = np.transpose(np.fromfunction(theta, (self.num_classes, self.num_features)))
        self.means = thetas[0]
        self.stddevs = thetas[1]
        
    def predict(self, X):
        if X.shape[1] != self.num_features:
            raise Exception("Wrong number of features")
            
        d = X.shape[0]
        
        # X.shape == (data, features)
        
        X = np.repeat(np.expand_dims(x, axis=2), 4, axis=2)
        # X.shape == (data, features, classes)
        
        
        for data in range(0, d):
            for feature in range(0, self.num_features):
                for class_ in range(0, self.num_classes):
                    mean, stddev = self.means[feature][class_], self.stddevs[feature][class_]
                    if self.feature_types[feature] == 'b':
                        X[data, feature, class_] = mean if X[data, feature, class_] == 1 else 1-mean
                    else:
                        X[data, feature, class_] = norm(mean,stddev).pdf(X[data, feature, class_])
        
        X = np.sum(X, axis = 1)
        # X.shape == (data, classes)
        
        y = np.argmax(X + self.logpi, axis=1)
        # y.shape == (data)
                
        return self.classes[y]

SyntaxError: invalid syntax (<ipython-input-6-c1dd752d8752>, line 30)

In [5]:
from sklearn.naive_bayes import MultinomialNB 

for nbc in [NBC(np.repeat('b', 16), 2), MultinomialNB()]:
    nbc.fit(X_train, y_train)
    y_hat = nbc.predict(X_test)
    test_accuracy = np.mean(y_hat == y_test)
    print test_accuracy

TypeError: 'dict' object is not callable

In [96]:
print X_train.reduce(lambda x, y:  x + y)

AttributeError: 'numpy.ndarray' object has no attribute 'reduce'

In [79]:
data = 3
features = 2
classes = 4
x = np.array([[1,2],[3,4],[5,6]])
x = np.repeat(np.expand_dims(x, axis=2), 4, axis=2)
print x
print x.shape

means = np.array([1,2,3,4])
x = 

x = np.sum(y, axis=1)
print y.shape
print y
logpi = np.array([10,20,30,40])
print logpi
y += logpi
print y
np.argmax(y, axis=1)

[[[1 1 1 1]
  [2 2 2 2]]

 [[3 3 3 3]
  [4 4 4 4]]

 [[5 5 5 5]
  [6 6 6 6]]]
(3, 2, 4)
(3, 4)
[[ 3  3  3  3]
 [ 7  7  7  7]
 [11 11 11 11]]
[10 20 30 40]
[[13 23 33 43]
 [17 27 37 47]
 [21 31 41 51]]


array([3, 3, 3])

In [112]:
np.log([1,1,2,2])

array([ 0.        ,  0.        ,  0.69314718,  0.69314718])

In [134]:
len(np.repeat('b', 16))

16